---
- name: Update apt repository and install required packages
  apt:
    update_cache: yes
    name:
      - gnupg
      - software-properties-common
      - curl
    state: present
  become: true

- name: Install HashiCorp GPG key
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Verify the GPG key fingerprint
  shell: |
    gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
  register: gpg_fingerprint_output
  changed_when: false
  become: true

- name: Add the official HashiCorp repository
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  args:
    creates: /etc/apt/sources.list.d/hashicorp.list
  become: true

- name: Update apt repository cache after adding HashiCorp repository
  apt:
    update_cache: yes
  become: true

- name: Install Terraform
  apt:
    name: terraform
    state: present
  become: true

- name: Verify Terraform install
  command: terraform -help
