---
- name: Create repos directory in home
  file:
    path: "{{ ansible_env.HOME }}/repos"
    state: directory

- name: Create symlink to /mnt/c/Users/FOO/Desktop/repos
  file:
    src: "/mnt/c/Users/{{ ansible_env.USER }}/Desktop/repos"
    dest: "{{ ansible_env.HOME }}/repos"
    state: link
